import { useEffect } from 'react';
import { useRouter } from 'next/router';
import Head from 'next/head';
import LoginForm from '@/components/LoginForm';

export default function Home() {
  const router = useRouter();

  useEffect(() => {
    // Check if auth_token exists in local storage
    const authToken = localStorage.getItem('auth_token');

    // Redirect to /dashboard if auth_token is present
    if (authToken) {
      router.push('/dashboard');
    }
  }, [router]);

  return (
    <>
      <Head>
        <title>Tabla</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <LoginForm />
      </main>
    </>
  );
}
